# Generated by Django 3.0.1 on 2020-07-29 14:32

import arbeitsplan.models
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Aufgabe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aufgabe', models.CharField(max_length=50, unique=True, validators=[arbeitsplan.models.validate_notDot])),
                ('anzahl', models.IntegerField(default=0, help_text='Wieviele Personen werden für diese Aufgabe gebraucht?', verbose_name='Anzahl benötigte Helfer')),
                ('stunden', models.IntegerField(default=0, help_text='Wieviele Stunden Arbeit pro Person?', verbose_name='Stunden')),
                ('datum', models.DateField(blank=True, help_text='Wann fällt die Aufgabe an? (freilassen möglich)', null=True)),
                ('bemerkung', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Aufgabe',
                'verbose_name_plural': 'Aufgaben',
                'ordering': ['aufgabe'],
            },
        ),
        migrations.CreateModel(
            name='Zuteilung',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('automatisch', models.BooleanField(default=False)),
                ('zusatzhelfer', models.IntegerField(default=0)),
                ('aufgabe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='arbeitsplan.Aufgabe')),
                ('ausfuehrer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Zuteilung',
                'verbose_name_plural': 'Zuteilungen',
            },
        ),
        migrations.CreateModel(
            name='StundenZuteilung',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uhrzeit', models.IntegerField(blank=True, null=True)),
                ('zuteilung', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arbeitsplan.Zuteilung')),
            ],
            options={
                'verbose_name': 'Zuteilung einer Stunde',
                'verbose_name_plural': 'Zuteilungen für einzelne Stunden',
            },
        ),
        migrations.CreateModel(
            name='Stundenplan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uhrzeit', models.IntegerField(help_text='Beginn')),
                ('anzahl', models.IntegerField(default=0, help_text='Wieviele Personen werden um diese Uhrzeit benötigt?')),
                ('aufgabe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arbeitsplan.Aufgabe')),
            ],
            options={
                'verbose_name': 'Stundenplan',
                'verbose_name_plural': 'Stundenpläne',
            },
        ),
        migrations.CreateModel(
            name='Mitglied',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mitgliedsnummer', models.CharField(default=0, help_text='Mitgliedsnummer', max_length=10)),
                ('zuteilungsbenachrichtigung', models.DateTimeField(default=datetime.datetime(1900, 1, 1, 0, 0), help_text='Wann war die letzte Benachrichtigung zu einer Zuteilung?', verbose_name='Letzte Benachrichtigung')),
                ('zuteilungBenachrichtigungNoetig', models.BooleanField(default=False, help_text='Muss an diese Nutzer eine Benachrichtigung wegen Änderung der Zuteilungen gesendet werden?', verbose_name='Benachrichtigung zu Zuteilungen nötig?')),
                ('zustimmungsDatum', models.DateTimeField(default=datetime.datetime(1900, 1, 1, 0, 0), help_text='Wann hat der Nutzer Zustimmung erteilt?', verbose_name='Datum der Zustimmung')),
                ('geburtsdatum', models.DateField(default=datetime.datetime(1900, 1, 1, 0, 0), help_text='Geburtsdatum des Mitglieds', verbose_name='Geburtstag')),
                ('strasse', models.CharField(default='', max_length=50, verbose_name='Strasse und Hausnummer')),
                ('plz', models.DecimalField(decimal_places=0, default=0, max_digits=5, verbose_name='PLZ')),
                ('gender', models.CharField(choices=[('M', 'M'), ('W', 'W')], default='M', max_length=1, verbose_name='Geschlecht')),
                ('ort', models.CharField(default='', max_length=50, verbose_name='Ort')),
                ('festnetz', phonenumber_field.modelfields.PhoneNumberField(blank=True, default='', max_length=128, region=None, verbose_name='Festnetznummer')),
                ('mobil', phonenumber_field.modelfields.PhoneNumberField(blank=True, default='', max_length=128, region=None, verbose_name='Mobilnummer')),
                ('status', models.CharField(choices=[('Er', 'Erwachsene'), ('Ju', 'Jugendliche'), ('Ss', 'Schüler, Studenten, BW, Zivi'), ('Ki', 'Kind in Familie'), ('Kf', 'Kind in Familie, beitragsfrei'), ('PM', 'Passives Mitglied'), ('Nm', 'Nichtmitglied'), ('Bf', 'Beitragsfreies Mitglied'), ('Pa', 'Partner aktives Mitglied'), ('Pp', 'Partner passives Mitglied')], default='Er', max_length=20, verbose_name='Mitgliedsstatus')),
                ('erstbenachrichtigt', models.BooleanField(default=False, help_text='Wurde die Erstbenachrichtigung mit Password bereits generiert?', verbose_name='Erstbenachrichtigung')),
                ('arbeitslast', models.IntegerField(default=10, help_text='Wieviele Stunden pro Jahr muss dieses Mitglied arbeiten?', verbose_name='Arbeitslast (h/Jahr)')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mitglied',
                'verbose_name_plural': 'Mitglieder',
            },
        ),
        migrations.CreateModel(
            name='Meldung',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('erstellt', models.DateField(auto_now_add=True)),
                ('veraendert', models.DateField(auto_now=True)),
                ('prefMitglied', models.IntegerField(choices=[(-1, 'Nein'), (0, 'Wenn es sein muss'), (1, 'Ok'), (2, 'Gerne!')], default=1, help_text='Haben Sie Vorlieben für diese Aufgabe?', verbose_name='Präferenz')),
                ('prefVorstand', models.IntegerField(choices=[(-1, 'Nein'), (0, 'Wenn es sein muss'), (1, 'Ok'), (2, 'Gerne!')], default=1, help_text='Trauen Sie diesem Mitglied die Aufgabe zu?')),
                ('bemerkung', models.TextField(blank=True)),
                ('bemerkungVorstand', models.TextField(blank=True)),
                ('aufgabe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='arbeitsplan.Aufgabe')),
                ('melder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Meldung',
                'verbose_name_plural': 'Meldungen',
            },
        ),
        migrations.CreateModel(
            name='Leistung',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('erstellt', models.DateTimeField(auto_now_add=True)),
                ('veraendert', models.DateTimeField()),
                ('benachrichtigt', models.DateTimeField(default=datetime.datetime(1900, 1, 1, 0, 0))),
                ('wann', models.DateField(help_text='An welchem Tag haben Sie die Leistung erbracht?')),
                ('zeit', models.DecimalField(decimal_places=1, help_text='Wieviel Zeit (in Stunden) haben Sie gearbeitet? Eingabe von Zentelstunden möglich. Je nach Browsereinstellung mit . oder , die Nachkommastelle abtrennen: 1.4 oder 1,4 für 1 Stunde 24 Minuten. ', max_digits=3)),
                ('status', models.CharField(choices=[('OF', 'Offen'), ('AK', 'Akzeptiert'), ('RU', 'Rückfrage'), ('NE', 'Abgelehnt')], default='OF', max_length=2)),
                ('bemerkung', models.TextField(blank=True)),
                ('bemerkungVorstand', models.TextField(blank=True, verbose_name='Bemerkung Vorstand')),
                ('aufgabe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='arbeitsplan.Aufgabe')),
                ('melder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Leistung',
                'verbose_name_plural': 'Leistungen',
            },
        ),
        migrations.CreateModel(
            name='Aufgabengruppe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gruppe', models.CharField(help_text='Aussagefähiger Name für Gruppe von Aufgaben', max_length=30)),
                ('bemerkung', models.TextField(blank=True)),
                ('verantwortlich', models.ForeignKey(help_text='Verantwortliches Vorstandsmitglied', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Aufgabengruppe',
                'verbose_name_plural': 'Aufgabengruppen',
                'ordering': ['gruppe'],
            },
        ),
        migrations.AddField(
            model_name='aufgabe',
            name='gruppe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='arbeitsplan.Aufgabengruppe'),
        ),
        migrations.AddField(
            model_name='aufgabe',
            name='teamleader',
            field=models.ForeignKey(blank=True, help_text='Ein optionaler Teamleader für die Aufgabe (nicht notwendig Vorstand)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teamleader_set', to=settings.AUTH_USER_MODEL, verbose_name='Team-Leader'),
        ),
        migrations.AddField(
            model_name='aufgabe',
            name='verantwortlich',
            field=models.ForeignKey(help_text='Verantwortliches Vorstandsmitglied', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
