# Generated by Django 3.0.1 on 2020-07-29 14:32

import boote.models
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Boat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(null=True, upload_to=boote.models.boat_img_path)),
                ('name', models.CharField(max_length=30)),
                ('active', models.BooleanField(default=True)),
                ('briefing', models.CharField(default='', max_length=2000, null=True)),
                ('remarks', models.CharField(max_length=2000, null=True)),
                ('club_boat', models.BooleanField(default=False)),
                ('booking_remarks', models.CharField(default='', max_length=2000, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BoatType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('url', models.CharField(max_length=256)),
                ('length', models.CharField(max_length=15)),
                ('beam', models.CharField(max_length=15)),
                ('draught', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(default=datetime.datetime.now)),
                ('status', models.IntegerField(default=1)),
                ('type', models.CharField(choices=[('PRV', 'Freie Nutzung'), ('AUS', 'Ausbildung'), ('REG', 'Regatta')], default='PRV', max_length=3)),
                ('date', models.DateField()),
                ('time_from', models.TimeField()),
                ('time_to', models.TimeField()),
                ('notified', models.BooleanField(default=False)),
                ('boat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boote.Boat')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BoatIssue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(default=1)),
                ('reported_date', models.DateField()),
                ('reported_descr', models.CharField(max_length=2000)),
                ('fixed_date', models.DateField(null=True)),
                ('fixed_descr', models.CharField(max_length=2000, null=True)),
                ('notified', models.BooleanField(default=False)),
                ('boat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boote.Boat')),
                ('fixed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_fixing', to=settings.AUTH_USER_MODEL)),
                ('reported_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_reporting', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='boat',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='boote.BoatType'),
        ),
    ]
